#pragma once

enum class HeightMapType {
    SPAWN_LOW,
    SPAWN_MEDIUM,
    SPAWN_HIGH,
    VERTICAL_LOW,
    VERTICAL_MEDIUM,
    VERTICAL_HIGH,
    HORIZONTAL_LOW,
    HORIZONTAL_MEDIUM,
    HORIZONTAL_HIGH,
    T_JUNCTION_LOW,
    T_JUNCTION_MEDIUM,
    T_JUNCTION_HIGH,
};

struct HeightMap {

};